# Generated by Django 3.1.5 on 2022-04-15 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Podaj imię autora książki', max_length=100)),
                ('last_name', models.CharField(help_text='Podaj nazwisko autora książki', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Urodzony - ')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Zmarł - ')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('summary', models.TextField(help_text='Wprowadz krotki opis ksiazki', max_length=1000, verbose_name='Opis książki')),
                ('isbn', models.CharField(help_text='13 znakowy <a href="https://www.isbn-international.org/content/what-isbn">numer ISBN</a>', max_length=13, verbose_name='ISBN')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author', verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wprowadż gatunek ksiażki (np. Romans)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wprowadż język (np. Polski)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalne ID dla kazdej ksiazki w calej księgarni.', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Wypożyczona do')),
                ('status', models.CharField(blank=True, choices=[('m', 'W trakcie renowacji'), ('o', 'Wypożyczona'), ('a', 'Dostępna'), ('r', 'Zarezerwowana')], default='m', help_text='Dostępność książki', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.book', verbose_name='Tytuł książki')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pożyczający')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Wybierz gatunek ksiazki.', to='catalog.Genre', verbose_name='Gatunek'),
        ),
    ]
