# Generated by Django 3.2.13 on 2022-04-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Wybierz język.', to='catalog.Language', verbose_name='Język'),
        ),
    ]
