# Generated by Django 3.2.13 on 2022-05-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Tytuł'),
        ),
    ]
